name: Build and Deploy Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and save Docker image
        run: |
          IMAGE_TAG=my-image-name-$(date +%Y%m%d%H%M%S)
          docker build -t $IMAGE_TAG .
          docker save $IMAGE_TAG > my-image.tar
        # Upload the Docker image as an artifact
      - name: Upload image artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-image
          path: my-image.tar

      - name: Print available Docker images
        run: docker images

      - name: Print runner's working directory
        run: |
          ls -R $GITHUB_WORKSPACE

      - name: Copy Docker Image to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: my-image.tar
          target: /root/
